
# Not an actual controller, it just publishes the joint state of the robot
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

# JointGroupPositionController for the arm, allows to set the position of the joints
panda_arm_effort_effort_controller:
    type: effort_controllers/JointGroupEffortController
    joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

# JointGroupPositionController for the gripper, allows to set the position of the joints
panda_hand_effort_effort_controller:
    type: effort_controllers/JointGroupEffortController
    joints:
        - panda_finger_joint1
        - panda_finger_joint2
